// frontend/components/ComparisonControls.vue
<script setup>
const props = defineProps({ model: Object });
const valueModes = [['totals', 'Totals'], ['round', 'Per round'], ['match', 'Per match']];
const defaults = ['overview', 'opening', 'rounds'];
function toggleSection(key) {
  const selected = new Set(props.model.sections.filter(section => section.active).map(section => section.key));
  selected.has(key) ? selected.delete(key) : selected.add(key);
  props.model.actions.sections(selected);
}
</script>

<template>
  <div class="quick-comparison-controls">
    <div class="quick-comparison-sections">
      <div class="scoreboard-section-bar scoreboard-control-row">
        <strong>Sections</strong>
        <div class="scoreboard-button-group scoreboard-section-buttons">
          <button type="button" class="scoreboard-preset-button" @click="model.actions.sections(defaults)">Default</button>
          <button type="button" class="scoreboard-preset-button" @click="model.actions.sections(model.sections.map(section => section.key))">All</button>
          <button v-for="section in model.sections" :key="section.key" type="button" class="scoreboard-section-button"
            :class="[`${section.style}-heading`, { active: section.active }]" :aria-pressed="section.active"
            @click="toggleSection(section.key)">{{ section.label }}</button>
        </div>
      </div>
      <div class="scoreboard-value-toggle scoreboard-control-row">
        <strong>Values</strong>
        <div class="scoreboard-button-group">
          <button v-for="[value, label] in valueModes" :key="value" type="button" :class="{ active: model.valueMode === value }"
            :aria-pressed="model.valueMode === value" @click="model.actions.valueMode(value)">{{ label }}</button>
        </div>
        <div class="scoreboard-utility-basis">
          <span>Utility yields</span>
          <button type="button" :disabled="model.valueMode === 'totals'" :class="{ active: model.perGrenadeUtility }"
            :aria-pressed="model.perGrenadeUtility" title="Use each relevant grenade type for damage, flash effects, and flash-assist yields"
            @click="model.actions.utilityBasis()">Per grenade</button>
        </div>
        <small class="scoreboard-control-note">{{ model.modeNote }}</small>
      </div>
    </div>
  </div>
</template>

// frontend/components/ComparisonControls.jsx
const valueModes = [['totals', 'Totals'], ['round', 'Per round'], ['match', 'Per match']];
const defaults = ['overview', 'opening', 'rounds'];

export default function ComparisonControls({ model }) {
  function toggleSection(key) {
    const selected = new Set(model.sections.filter(section => section.active).map(section => section.key));
    selected.has(key) ? selected.delete(key) : selected.add(key);
    model.actions.sections(selected);
  }
  return <div className="quick-comparison-controls">
    <div className="quick-comparison-sections">
      <div className="scoreboard-section-bar scoreboard-control-row">
        <strong>Sections</strong>
        <div className="scoreboard-button-group scoreboard-section-buttons">
          <button type="button" className="scoreboard-preset-button" onClick={() => model.actions.sections(defaults)}>Default</button>
          <button type="button" className="scoreboard-preset-button" onClick={() => model.actions.sections(model.sections.map(section => section.key))}>All</button>
          {model.sections.map(section => <button key={section.key} type="button"
            className={`scoreboard-section-button ${section.style}-heading${section.active ? ' active' : ''}`}
            aria-pressed={section.active} onClick={() => toggleSection(section.key)}>{section.label}</button>)}
        </div>
      </div>
      <div className="scoreboard-value-toggle scoreboard-control-row">
        <strong>Values</strong>
        <div className="scoreboard-button-group">
          {valueModes.map(([value, label]) => <button key={value} type="button" className={model.valueMode === value ? 'active' : undefined}
            aria-pressed={model.valueMode === value} onClick={() => model.actions.valueMode(value)}>{label}</button>)}
        </div>
        <div className="scoreboard-utility-basis">
          <span>Utility yields</span>
          <button type="button" disabled={model.valueMode === 'totals'} className={model.perGrenadeUtility ? 'active' : undefined}
            aria-pressed={model.perGrenadeUtility} title="Use each relevant grenade type for damage, flash effects, and flash-assist yields"
            onClick={() => model.actions.utilityBasis()}>Per grenade</button>
        </div>
        <small className="scoreboard-control-note">{model.modeNote}</small>
      </div>
    </div>
  </div>;
}
